#! /bin/sh
if [ $# -gt 0 ]; then
    wall="$1"
else
    wall=$(find $HOME/Pictures/Wall/ -type f | shuf -n 1)
fi
xwallpaper --zoom $wall 
wal -i $wall >/dev/null
sed -i '/SchemeUrg/d' $HOME/.cache/wal/colors-wal-dwm.h
xdotool key alt+F5
betterlockscreen -u $wall
